# Generated by Django 2.1.4 on 2018-12-08 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.PositiveIntegerField(max_length=11, primary_key=True, serialize=False)),
                ('nombreComuna', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('idListaCompra', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('costoPresupuestado', models.PositiveIntegerField()),
                ('costoReal', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ListaCompraProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productoComprado', models.BooleanField()),
                ('costoPresupuestado', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigoProducto', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=25)),
                ('costoProducto', models.PositiveIntegerField()),
                ('notasAdicionales', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProvincia', models.PositiveIntegerField(max_length=11)),
                ('nombreProvincia', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRegion', models.PositiveSmallIntegerField(max_length=11)),
                ('nombreRegion', models.CharField(max_length=64)),
                ('regionOrdinal', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('codigoTienda', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nombreTienda', models.CharField(max_length=50)),
                ('nombreSucursal', models.CharField(max_length=50, null=True)),
                ('direccionSucursal', models.CharField(max_length=64)),
                ('comunaSucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.Comuna')),
                ('regionSucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('contrasennaUsuario', models.CharField(max_length=14)),
                ('nombreUsuario', models.CharField(max_length=25)),
                ('apellidosUsuario', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioListaCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idListaCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.ListaCompra')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='provincia',
            name='regionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.Region'),
        ),
        migrations.AddField(
            model_name='listacompraproducto',
            name='codigoProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.Producto'),
        ),
        migrations.AddField(
            model_name='listacompraproducto',
            name='idListaCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.ListaCompra'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='idProvincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.Provincia'),
        ),
    ]
