# Generated by Django 2.1.4 on 2018-12-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_auto_20181207_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provincia',
            name='id',
        ),
        migrations.RemoveField(
            model_name='region',
            name='id',
        ),
        migrations.AlterField(
            model_name='provincia',
            name='idProvincia',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='idRegion',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
