# Generated by Django 2.1.4 on 2018-12-08 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0003_auto_20181207_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='costoProducto',
        ),
    ]
