# Generated by Django 2.1.4 on 2018-12-08 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0005_productotienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productotienda',
            name='codigoProducto',
        ),
        migrations.DeleteModel(
            name='ProductoTienda',
        ),
    ]
