# Generated by Django 2.1.4 on 2018-12-09 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0006_auto_20181208_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.Producto')),
                ('codigoTienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.Tienda')),
            ],
        ),
    ]
