# Generated by Django 2.1.4 on 2018-12-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0007_productotienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='productotienda',
            name='costoProducto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='miembroStaff',
            field=models.BooleanField(default=False),
        ),
    ]
